import 'package:medilink/shared/enums/dosage_type.dart';
import 'package:medilink/shared/enums/medicine_type.dart';

class MedicineModel {
  // I do "?" cau'z id is automatically generated by Supabase so it's not required to instanciate the object
  final String? id;
  final String name;
  final String dosage;
  final UniteDosage unit;
  final MedicineType type;

  const MedicineModel({
    this.id,
    required this.name,
    required this.dosage,
    required this.unit,
    required this.type,
  });

  MedicineModel copyWith({
    String? id,
    String? name,
    String? dosage,
    UniteDosage? unit,
    MedicineType? type,
  }) {
    return MedicineModel(
      id: id ?? this.id,
      name: name ?? this.name,
      dosage: dosage ?? this.dosage,
      unit: unit ?? this.unit,
      type: type ?? this.type,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'name': name,
      'dosage': dosage,
      'unit': unit.code,
      'type': type.name,
    };
  }

  factory MedicineModel.fromJson(Map<String, dynamic> json) {
    return MedicineModel(
      id: (json['id'] ?? json['uid']) as String?,
      name: (json['name'] ?? '') as String,
      dosage: (json['dosage'] ?? '') as String,
      unit: UniteDosage.fromCode((json['unit'] ?? '') as String),
      type: MedicineType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => MedicineType.compressed,
      ),
    );
  }

  @override
  String toString() => 'MedicineModel(name: $name, dosage: $dosage ${unit.code})';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is MedicineModel && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}
